seed: 1337

dataset:
  name: mnist
  params:
    data_dir: ./data
    batch_size: 128
    num_workers: 4


model:
  backbone:
    name: simple_cnn
    params:
      out_dim: 128
  head:
    name: linear
    params:
      in_dim: 128
      num_classes: 10


train:
  epochs: 5
  lr: 0.001
  weight_decay: 0.0001
  device: cpu # swap to "cuda"
  ckpt_dir: ./checkpoints
  log_every: 50     # training steps
  eval_every: 1     # epochs


eval:
  batch_size: 128


logging:
  use_tensorboard: false
  use_wandb: false
  project_name: tverskycv
  run_name: null